In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.transform import Rotation as R

In [4]:
a = np.zeros([44])
b = np.zeros([4])

In [7]:
np.hstack((a, b)).shape

(48,)

In [40]:
df = pd.read_csv('Joints CSV/walk9_1QuatRot.csv')

In [41]:
df

LeftUpLeg.X  LeftUpLeg.Y  LeftUpLeg.Z  LeftUpLeg.W  RightUpLeg.X  \
0       0.015097    -0.009735    -0.237774     0.971154     -0.341619   
1       0.030204     0.001146    -0.232719     0.972074     -0.352193   
2       0.043930     0.013243    -0.226059     0.973032     -0.360574   
3       0.059133     0.025625    -0.221390     0.973054     -0.366914   
4       0.076159     0.036967    -0.217275     0.972432     -0.370440   
..           ...          ...          ...          ...           ...   
128    -0.244248     0.010659    -0.079054     0.966426     -0.036533   
129    -0.260439    -0.009739    -0.086529     0.961556     -0.024492   
130    -0.296990    -0.003613    -0.060573     0.952951     -0.006541   
131    -0.307112    -0.023635    -0.060068     0.949482      0.006919   
132    -0.315824    -0.027637    -0.056256     0.946745      0.031206   

     RightUpLeg.Y  RightUpLeg.Z  RightUpLeg.W  LeftLeg.X  LeftLeg.Y  ...  \
0        0.073504      0.079287      0.933599   0.268772   0.082364  ...   
1        0.081491      0.078165      0.929091   0.251936   0.078915  ...   
2        0.093175      0.076187      0.924933   0.233688   0.074814  ...   
3        0.102814      0.071392      0.921795   0.214097   0.070017  ...   
4        0.110330      0.066921      0.919850   0.192753   0.064362  ...   
..            ...           ...           ...        ...        ...  ...   
128      0.075989      0.271475      0.958745   0.839616  -0.136685  ...   
129      0.063606      0.267514      0.961140   0.836178  -0.131823  ...   
130      0.069133      0.286807      0.955468   0.836173  -0.131818  ...   
131      0.054028      0.287360      0.956273   0.830256  -0.123668  ...   
132      0.041550      0.292298      0.954914   0.821906  -0.112605  ...   

     RightForeArm.W  LeftHand.X  LeftHand.Y  LeftHand.Z  LeftHand.W  \
0          0.698867   -0.169611         0.0         0.0    0.985511   
1          0.695398   -0.177969         0.0         0.0    0.984036   
2          0.688671   -0.186706         0.0         0.0    0.982416   
3          0.678321   -0.197789         0.0         0.0    0.980245   
4          0.666986   -0.209378         0.0         0.0    0.977835   
..              ...         ...         ...         ...         ...   
128        0.092258   -0.290088         0.0         0.0    0.957000   
129        0.074284   -0.293857         0.0         0.0    0.955849   
130        0.054218   -0.293899         0.0         0.0    0.955837   
131        0.032914   -0.294005         0.0         0.0    0.955804   
132        0.012402   -0.295799         0.0         0.0    0.955250   

     RightHand.X  RightHand.Y  RightHand.Z  RightHand.W      Time  
0       0.044109          0.0          0.0     0.999027  0.133333  
1       0.039221          0.0          0.0     0.999231  0.141666  
2       0.034314          0.0          0.0     0.999411  0.149999  
3       0.030506          0.0          0.0     0.999535  0.158333  
4       0.028595          0.0          0.0     0.999591  0.166666  
..           ...          ...          ...          ...       ...  
128    -0.043214          0.0          0.0     0.999066  1.199995  
129    -0.038250          0.0          0.0     0.999268  1.208328  
130    -0.033621          0.0          0.0     0.999435  1.216662  
131    -0.030186          0.0          0.0     0.999544  1.224995  
132    -0.026390          0.0          0.0     0.999652  1.233328  

[133 rows x 49 columns]

In [42]:
a = df.iloc[0]
print(a)

LeftUpLeg.X       0.015097
LeftUpLeg.Y      -0.009735
LeftUpLeg.Z      -0.237774
LeftUpLeg.W       0.971154
RightUpLeg.X     -0.341619
RightUpLeg.Y      0.073504
RightUpLeg.Z      0.079287
RightUpLeg.W      0.933599
LeftLeg.X         0.268772
LeftLeg.Y         0.082364
LeftLeg.Z         0.049598
LeftLeg.W         0.958393
RightLeg.X        0.766236
RightLeg.Y        0.049985
RightLeg.Z       -0.257825
RightLeg.W        0.586439
LeftFoot.X       -0.060422
LeftFoot.Y       -0.074105
LeftFoot.Z        0.004951
LeftFoot.W        0.995406
RightFoot.X       0.087478
RightFoot.Y      -0.041119
RightFoot.Z      -0.006366
RightFoot.W       0.995297
LeftArm.X         0.353201
LeftArm.Y         0.165780
LeftArm.Z        -0.625786
LeftArm.W         0.675395
RightArm.X        0.088766
RightArm.Y       -0.327065
RightArm.Z        0.566555
RightArm.W        0.751109
LeftForeArm.X    -0.544691
LeftForeArm.Y     0.478727
LeftForeArm.Z     0.687006
LeftForeArm.W    -0.046409
RightForeArm.X   -0.416088
R

In [43]:
a.to_dict()

{'LeftUpLeg.X': 0.015097343477146478,
 'LeftUpLeg.Y': -0.009735035902250269,
 'LeftUpLeg.Z': -0.2377743918049266,
 'LeftUpLeg.W': 0.9711542812023805,
 'RightUpLeg.X': -0.34161922426597746,
 'RightUpLeg.Y': 0.07350375280955103,
 'RightUpLeg.Z': 0.07928672577162638,
 'RightUpLeg.W': 0.9335990140586264,
 'LeftLeg.X': 0.2687720872756651,
 'LeftLeg.Y': 0.08236444824542108,
 'LeftLeg.Z': 0.049598253002577225,
 'LeftLeg.W': 0.958393278391393,
 'RightLeg.X': 0.7662356341190012,
 'RightLeg.Y': 0.04998513449146042,
 'RightLeg.Z': -0.25782458315440976,
 'RightLeg.W': 0.5864391900763265,
 'LeftFoot.X': -0.060422050652931124,
 'LeftFoot.Y': -0.0741048060479728,
 'LeftFoot.Z': 0.0049508139011430145,
 'LeftFoot.W': 0.99540601914857,
 'RightFoot.X': 0.08747798107072002,
 'RightFoot.Y': -0.04111883694492245,
 'RightFoot.Z': -0.006366336006188331,
 'RightFoot.W': 0.9952970982786716,
 'LeftArm.X': 0.3532006273162405,
 'LeftArm.Y': 0.16577957180145342,
 'LeftArm.Z': -0.6257861539507037,
 'LeftArm.W': 0.67

In [44]:
#  Root = 0, lhipjoint = 3, lfemur = 6, ltibia = 9, rhipjoint = 12, rfemur = 15, rtibia = 18
a.to_list()

[0.015097343477146478,
 -0.009735035902250269,
 -0.2377743918049266,
 0.9711542812023805,
 -0.34161922426597746,
 0.07350375280955103,
 0.07928672577162638,
 0.9335990140586264,
 0.2687720872756651,
 0.08236444824542108,
 0.049598253002577225,
 0.958393278391393,
 0.7662356341190012,
 0.04998513449146042,
 -0.25782458315440976,
 0.5864391900763265,
 -0.060422050652931124,
 -0.0741048060479728,
 0.0049508139011430145,
 0.99540601914857,
 0.08747798107072002,
 -0.04111883694492245,
 -0.006366336006188331,
 0.9952970982786716,
 0.3532006273162405,
 0.16577957180145342,
 -0.6257861539507037,
 0.6753948030302921,
 0.08876556996892143,
 -0.3270653098668411,
 0.566554578995064,
 0.7511090904053321,
 -0.5446913398693738,
 0.4787272523916707,
 0.6870063832320373,
 -0.046408959127123284,
 -0.41608754756843497,
 0.28410180320543704,
 -0.5076837044653302,
 0.6988666356281888,
 -0.1696109560991915,
 0.0,
 0.0,
 0.9855110976397568,
 0.04410935283179472,
 0.0,
 0.0,
 0.9990267088485474,
 0.1333328]

In [46]:
import pybullet_envs
import gym

In [47]:
env = gym.make('HumanoidBulletEnv-v0')

In [48]:
# env.close()

In [49]:
obs = env.reset()

In [50]:
print(len(obs), obs)

44 [ 5.9999996e-01  6.9100463e-07  1.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00 -0.0000000e+00
 -5.2742977e-02  0.0000000e+00  3.9381334e-01  0.0000000e+00
  7.0315190e-02  0.0000000e+00  3.4107587e-01  0.0000000e+00
  3.8131177e-01  0.0000000e+00  7.3970056e-01  0.0000000e+00
  9.9446213e-01  0.0000000e+00  9.3073058e-01  0.0000000e+00
  3.1005520e-01  0.0000000e+00  6.4398402e-01  0.0000000e+00
  1.0549511e+00  0.0000000e+00  2.3961198e-01  0.0000000e+00
  2.3867390e-01  0.0000000e+00  3.3552343e-01  0.0000000e+00
 -1.8468004e-01  0.0000000e+00 -1.9920982e-01  0.0000000e+00
  2.9497612e-01  0.0000000e+00  0.0000000e+00  0.0000000e+00]


In [51]:
for j in env.jdict:
    print(j, env.jdict[j].current_relative_position())

abdomen_z (-0.05274297491108334, 0.0)
abdomen_y (0.39381333368574223, 0.0)
abdomen_x (0.07031519258880688, 0.0)
right_hip_x (0.3410758751841874, 0.0)
right_hip_z (0.3813117641860396, 0.0)
right_hip_y (0.7397005502556482, 0.0)
right_knee (0.9944621204311415, 0.0)
left_hip_x (0.9307306108900959, 0.0)
left_hip_z (0.3100551836072859, 0.0)
left_hip_y (0.6439840161452175, 0.0)
left_knee (1.0549510449184736, 0.0)
right_shoulder1 (0.23961198552024646, 0.0)
right_shoulder2 (0.23867390281120943, 0.0)
right_elbow (0.3355234187619139, 0.0)
left_shoulder1 (-0.18468004220074788, 0.0)
left_shoulder2 (-0.1992098312532584, 0.0)
left_elbow (0.2949761283856279, 0.0)


In [52]:
env.jdict['right_knee'].current_position()

(-0.04254226953784852, 0.0)

In [53]:
env.jdict['right_knee']

In [54]:
for p in env.parts:
    if('link' not in p):
        print(p, R.from_quat(env.parts[p].get_pose()[3:]).as_quat())

torso [0. 0. 0. 1.]
lwaist [-2.88373799e-04 -1.79195867e-02 -2.07086298e-02  9.99624909e-01]
pelvis [ 0.02113632 -0.02035891 -0.02027548  0.99936364]
right_thigh [-0.02281966 -0.00288834  0.02747546  0.9993578 ]
right_shin [-0.02339889  0.01836818  0.02698388  0.99919316]
right_foot [-0.02339889  0.01836818  0.02698388  0.99919316]
left_thigh [-0.01475097 -0.06276918 -0.03979508  0.99712526]
left_shin [-0.01556085 -0.08312617 -0.03948543  0.99563487]
left_foot [-0.01556085 -0.08312617 -0.03948543  0.99563487]
right_upper_arm [ 0.03570089 -0.01329974  0.04591542  0.99821858]
right_lower_arm [ 0.03638598 -0.03553482  0.06659945  0.99648274]
left_upper_arm [-0.00641153 -0.00889509 -0.01507875  0.99982619]
left_lower_arm [-0.00643617 -0.0129205  -0.01905276  0.99971427]
floor [0. 0. 0. 1.]


In [67]:
actualLThighQ = R.from_quat(env.parts['left_thigh'].get_pose()[3:])
x, y, z, w = df['LeftUpLeg.X'].iloc[0], df['LeftUpLeg.Y'].iloc[0], df['LeftUpLeg.Z'].iloc[0], df['LeftUpLeg.W'].iloc[0]
refLThighQ = R.from_quat([x, y, z, w])

print(actualLThighQ.as_quat(), refLThighQ.as_quat())

[-0.01475097 -0.06276918 -0.03979508  0.99712526] [ 0.01509734 -0.00973504 -0.23777439  0.97115428]


In [68]:
shortestAngle = refLThighQ * actualLThighQ.inv()

In [69]:
print(shortestAngle.as_quat())
print(shortestAngle.as_euler('zyx', degrees=True))

[-0.0439169  -0.04714331  0.19735245 -0.97821308]
[-23.03824498   4.29537232   6.01692864]


In [73]:
np.clip(np.abs(shortestAngle.as_euler('zyx', degrees=True)), 0.001, 180)

array([23.03824498,  4.29537232,  6.01692864])

In [66]:
shortestAngle.magnitude()

0.679960633151861

In [76]:
env.action_space.sample()

array([ 0.49336505, -0.5659901 , -0.19578922, -0.61176175, -0.9745941 ,
        0.5139381 ,  0.61837643,  0.73036206, -0.8472857 , -0.24802065,
       -0.6941837 ,  0.8466927 , -0.8028988 ,  0.5497886 ,  0.7589527 ,
       -0.07189947, -0.89333844], dtype=float32)

In [77]:
def vectorFrom2Points(p1, p2):
    vec =  (p2[0] - p1[0], p2[1] - p1[1], p2[2] - p1[2])
    mag = np.sqrt(np.square(vec[0]) + np.square(vec[1]) + np.square(vec[2]))
    return (vec[0] / mag, vec[1] / mag, vec[2] / mag)

def angle2Vec(v1, v2):
    return np.rad2deg(np.arccos(v1[0] * v2[0] + v1[1] * v2[1] + v1[2] * v2[2]))

def calc(obs, joint, idxObs1, idxObs2, idxJoint1, idxJoint2):
    v1 = vectorFrom2Points(obs[idxObs1:idxObs1+3], obs[idxObs2:idxObs2+3])
    v2 = vectorFrom2Points((joint[idxJoint1+2], joint[idxJoint1], joint[idxJoint1+1]), (joint[idxJoint2+2], joint[idxJoint2], joint[idxJoint2+1]))
    print(v1, v2)
    return angle2Vec(v1, v2)

In [87]:
v1= vectorFrom2Points(env.parts['left_thigh'].get_position(), env.parts['left_shin'].get_position())
v11= vectorFrom2Points(env.parts['right_thigh'].get_position(), env.parts['right_shin'].get_position())
v12= vectorFrom2Points(env.parts['left_shin'].get_position(), env.parts['left_foot'].get_position())
v112= vectorFrom2Points(env.parts['right_shin'].get_position(), env.parts['right_foot'].get_position())
print(v1)
print(v11)
print(v12)
print(v112)

(-0.014417151127814018, -0.09271804146556754, -0.9955880224973315)
(0.017526079288898426, -0.015957129442920086, -0.9997190638197818)
(-0.06482104823886731, -0.07110455415698512, -0.9953604242099194)
(0.03677947468358527, -0.03295631600348164, -0.9987798313329511)


In [80]:
f

rootX          3.822670
rootY         17.937000
rootZ         14.864600
lhipjointX     2.361133
lhipjointY    16.089701
lhipjointZ    14.358369
lfemurX        2.466475
lfemurY        9.123412
lfemurZ       16.585949
ltibiaX        2.640510
ltibiaY        3.273635
ltibiaZ       21.775475
rhipjointX     4.923902
rhipjointY    16.021793
rhipjointZ    14.235148
rfemurX        4.714602
rfemurY        9.371562
rfemurZ       10.571028
rtibiaX        4.544611
rtibiaY        1.750538
rtibiaZ       11.363701
Name: 0, dtype: float64

In [88]:
f = df.iloc[0]
v2 = vectorFrom2Points((f['lhipjointX'], f['lhipjointZ'], f['lhipjointY']), (f['lfemurX'], f['lfemurZ'], f['lfemurY']))
v22 = vectorFrom2Points((f['rhipjointX'], f['rhipjointZ'], f['rhipjointY']), (f['rfemurX'], f['rfemurZ'], f['rfemurY']))
v23 = vectorFrom2Points((f['lfemurX'], f['lfemurZ'], f['lfemurY']), (f['ltibiaX'], f['ltibiaZ'], f['ltibiaY']))
v223 = vectorFrom2Points((f['rfemurX'], f['rfemurZ'], f['rfemurY']), (f['rtibiaX'], f['rtibiaZ'], f['rtibiaY']))
print(v2)
print(v22)
print(v23)
print(v223)

(0.01440177048090451, 0.3045415747077599, -0.9523901607437643)
(-0.027554916991446507, -0.4823918897823306, -0.8755220107009453)
(0.02224989816198715, 0.6634651993448776, -0.7478762406241043)
(-0.022180503617343854, 0.10342777487665854, -0.9943896221518727)


In [89]:
print(angle2Vec(v1, v2))
print(angle2Vec(v11, v22))
print(angle2Vec(v12, v23))
print(angle2Vec(v112, v223))

23.11129940361541
28.05570909043261
45.90989598620124
8.524753331624154


In [87]:
# Root -> r hip 
calc(obs, f, 8, 11, 0, 12)

(-0.1577801, 0.06641376, -0.9852384) (-0.2740133669520237, 0.47938874187604225, -0.8337284383383603)


26.29913561575083

In [29]:
def decipher_obs(obs):
    # z - self.initial_z,
    # np.sin(angle_to_target),
    # np.cos(angle_to_target),
    # 0.3 * vx,
    # 0.3 * vy,
    # 0.3 * vz,  # 0.3 is just scaling typical speed into -1..+1, no physical sense here
    # r,
    # p
    return {
        "deltaZ": obs[0],
        "sinAngleTarget": obs[1],
        "cosAngleTarget": obs[2],
        "vx": obs[3],
        "vy": obs[4],
        "vz": obs[5],
        "rBody": obs[6],
        "pBody": obs[7],
        "joints": obs[8:-2],
        "foot_contact": obs[-2:]
    }

In [31]:
d_obs = decipher_obs(obs)

In [32]:
d_obs['joints']

array([ 0.05812395,  0.        ,  0.38102156,  0.        , -0.00292499,
        0.        ,  0.6420605 ,  0.        ,  0.2521042 ,  0.        ,
        0.74473894,  0.        ,  1.0854613 ,  0.        ,  0.48315504,
        0.        ,  0.37431684,  0.        ,  0.64857244,  0.        ,
        1.0154244 ,  0.        ,  0.13077   ,  0.        ,  0.14582019,
        0.        ,  0.20516627,  0.        , -0.1206604 ,  0.        ,
       -0.23286505,  0.        ,  0.3270485 ,  0.        ], dtype=float32)

In [33]:
d_obs['joints'].shape

(34,)

In [65]:
env.close()

In [24]:
t = [1,2,3,4,5,6,7,8,9,10]

In [27]:
t[3:-1]

[4, 5, 6, 7, 8, 9]

In [90]:
t = {'a': 2, 'b':3}

In [93]:
list(t.values())

[2, 3]